apiVersion: v1
kind: LimitRange
metadata:
  name: backup-limits
  namespace: vhp-backup
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 200m
      memory: 512Mi
    type: Container