apiVersion: v1
kind: ResourceQuota
metadata:
  name: backup-quota
  namespace: vhp-backup
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "5"