apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vhp-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@senindomainin.com # Burayı güncellemeyi unutma!
    privateKeySecretRef:
      name: vhp-letsencrypt-prod-key
    solvers:
    - http01:
        ingress:
          class: vhp-nginx