# Not: Cert-Manager genellikle Helm ile kurulur ancak biz burada
# senin yap覺land覺rmana uygun custom tan覺mlar覺 tutuyoruz.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vhp-panel-cert
  namespace: vhp-cert
spec:
  secretName: vhp-panel-tls
  issuerRef:
    name: vhp-letsencrypt-prod
    kind: ClusterIssuer
  commonName: panel.vhp-platform.com
  dnsNames:
  - panel.vhp-platform.com